{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "embedder-service.secretName" . }}
  labels:
    {{- include "embedder-service.labels" . | nindent 4 }}
    secret.omnipdf.local/type: service-credentials
type: Opaque
data:
  {{- with .Values.secrets.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}