{{- if .Values.serviceEntries.enabled }}
{{- range .Values.serviceEntries.entries }}
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .name }}
  labels:
    {{- include "istio-gateway.labels" $ | nindent 4 }}
spec:
  hosts:
    {{- toYaml .hosts | nindent 4 }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  location: {{ .location }}
  resolution: {{ .resolution }}
{{- end }}
{{- end }}