{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  labels:
    {{- include "istio-gateway.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.virtualService.hosts | nindent 4 }}
  gateways:
    {{- toYaml .Values.virtualService.gateways | nindent 4 }}
  http:
    {{- range .Values.virtualService.routes }}
    - match:
        {{- toYaml .match | nindent 8 }}
      {{- if .rewrite }}
      rewrite:
        {{- toYaml .rewrite | nindent 8 }}
      {{- end }}
      route:
        {{- toYaml .route | nindent 8 }}
      {{- if .priority }}
      priority: {{ .priority }}
      {{- end }}
    {{- end }}
{{- end }}